### ISSUE TITLE
TicketMonster did not start

### ISSUE THREAD

**Issue by cbolz** [RedHatDemos/RHS-Infrastructure_Migration#47]
after deploying the lab the TicketMonster application gave an "bad gateway" error

I recommend adding steps on how to recover from this error

**Comment by mperezco** [comment]
Instructions added to guide in order to make users check VMs.

**Comment by mperezco** [comment]
Reviewed and modified autostart in vSphere 5.5

**Comment by mperezco** [comment]
Shutdown before creating blueprints done keeping NFS server for last and wait until others are down.

**Comment by mperezco** [comment]
Startup procedure starts Storage VM first

**Comment by mperezco** [comment]
Updated Ansible in the Workstation to 2.6
Created a playbook to start VMs
https://github.com/RedHatDemos/RHS-Infrastructure_Migration/blob/master/playbooks/start_vms.yml
Added it to` workstation` during boot.
