### ISSUE TITLE
Wrong instructions in Create an Migration Plan

### ISSUE THREAD

**Issue by cbolz** [RedHatDemos/RHS-Infrastructure_Migration#58]
https://github.com/RedHatDemos/RHS-Infrastructure_Migration/blob/master/doc/insfrastructure_migration-lab_guide.adoc#44-create-an-migration-plan

step 3:
In the step 1 of the wizard, General, select the Infrastructure Mapping to be used, ticket-monster-mapping, add the name ticket-monster-plan-lb and click next.

But it should describe how to create a migration plan, not a mapping (that was the previous chapter)

**Comment by mperezco** [comment]
In the migration plan the mapping has to be selected in the drop down menu

**Comment by mperezco** [comment]
Added a drop down menu explanation 34e5a55
