### ISSUE TITLE
broken link to deployment guide

### ISSUE THREAD

**Issue by cbolz** [RedHatDemos/RHS-Infrastructure_Migration#59]
"If you want a deeper knowledge on how the whole Infrastructure Migration works, you may want to read the Deployment guide."

The link is broken - returns a 404 error: https://github.com/RedHatDemos/RHS-Infrastructure_Migration/blob/master/doc/insfrastructure_migration_v2-deployment.adoc

**Comment by mperezco** [comment]
Fixed on commit b1c733a
