### ISSUE TITLE
FAQ out of date

### ISSUE THREAD

**Issue by cbolz** [RedHatDemos/RHS-Infrastructure_Migration#60]
AFAIK this is already implemented:

How can an Ansible post migration job be executed?
This feature is initially planned for June.

From: https://github.com/RedHatDemos/RHS-Infrastructure_Migration/blob/master/doc/insfrastructure_migration-vm_conversion_faq.adoc

**Comment by mperezco** [comment]
Fixed 391c9b7 cd48bc3 640b8ab
