### ISSUE TITLE
Infrastructure Mapping Fails

### ISSUE THREAD

**Issue by scalio31337** [RedHatDemos/RHS-Infrastructure_Migration#61]
On In the step 2 of the wizard, Clusters, select Source Cluster as vSphere\DC01\Cluster01 and Target Cluster as RHV\CoolDataCenter\TrustedCluster and click Add Mapping, then click next. I get the Source Clusters listed properly but in the Target Cluster there is a listing of five different targets:

RHV/CoolDataCenter/TrustedCluster
TrustedCluster
TrustedCluster
TrustedCluster
TrustedCluster

Clicking on the RHV/CoolDataCenter/TrustedCluster does not then expose any datastores listed in the next pane when going through the steps.

**Comment by bthurber** [comment]
Howdy!  Ravello has been having performance issues today which may be impacting the demo.  Can you try reordering and report the results?

Thanks!

**Comment by ffirg** [comment]
I have also just encountered this same original issue. Didn't refresh though.

**Comment by ffirg** [comment]
I can confirm that the Refresh step 3 section 4.1 works, and have now been able to see the datastores and complete the mapping. Happy camper.

**Comment by ffirg** [comment]
@scalio31337 the refresh seems to fix it. Want to close this one off?

**Comment by mperezco** [comment]
thanks @scalio31337 @ffirg
