### ISSUE TITLE
When a migration fails, you cannot download the log from the CF GUI

### ISSUE THREAD

**Issue by ffirg** [RedHatDemos/RHS-Infrastructure_Migration#64]
Hit Download Log->Migration Log and it fails with:
Failed to download "jboss0.log". Reason - "The location of transformation log was not set. Download of transformation log aborted."

**Comment by ffirg** [comment]
You seem to get this when you setup kvm2 as a transformation host and it gets selected during the migration. If you unset the vars for this host and use kvm1, you can download the log.

**Comment by bthurber** [comment]
Can you describe how you enabled the transformation host?  Did you just tag it or did you also run the enable conversion host playbook against that machine as well?

**Comment by ffirg** [comment]
I just set the variables as per the migration guide. It's a little confusing as it talks about kvm1 but screenshots show kvm2. It is missing a step? I notice there's no virt-v2v-wrapper.py on kvm2.

**Comment by bthurber** [comment]
OK.  Makes sense then.  If it's tagged but not enabled using the playbook then migrations to it will fail.  Appears we need to update the lab guide with new screen shots.  @mperezco

**Comment by mperezco** [comment]
@ffirg Were you using the deployment guide or the migration guide?

**Comment by ffirg** [comment]
migration

**Comment by mperezco** [comment]
fixed
