### ISSUE TITLE
VM migrations failing out-of-the-box

### ISSUE THREAD

**Issue by ffirg** [RedHatDemos/RHS-Infrastructure_Migration#65]
A newly provisioned RHPDS infra migration demo.
The DB was powered off and so ansible checks failed:
db.example.com | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh_exchange_identification: Connection closed by remote host\r\n",
    "unreachable": true
}

Powered on but couldn't seem to hit the Ticket monster URL

Tried a couple of migrations for lb and jboss0, both failed. Surely these should work regardless of the above error?

**Comment by bthurber** [comment]
Sounds like the backend Ravello env is having issues.  I would recommend deleting and re-ordering the demo/lab.  These are not common issues.

**Comment by ffirg** [comment]
I didn't need to delete/re-order, somehow it came back. Might be when I tried to migrate one of the VMs (playbooks doing stuff to the DB in preparation?)

**Comment by bthurber** [comment]
Sounds like Ravello was having some networking/communication issues.  We don't execute any pre/post playbooks for migration of the VMs at this time.  Maybe an enhancement we add in the future.

**Comment by ffirg** [comment]
Could be, let's close for now and if I encounter again, I'll re-open.
