### ISSUE TITLE
out of date screenshots

### ISSUE THREAD

**Issue by cbolz** [RedHatDemos/RHS-Infrastructure_Migration#68]
The following two screenshots do not match the current version of CF (they have a blue navigation bar on top instead of the grey one):
https://github.com/RedHatDemos/RHS-Infrastructure_Migration/blob/master/doc/images/cloudforms_infrastructure_providers_2.png

https://github.com/RedHatDemos/RHS-Infrastructure_Migration/raw/master/doc/images/cloudforms_infrastructure_providers_3.png

**Comment by cbolz** [comment]
same problem here:

https://github.com/RedHatDemos/RHS-Infrastructure_Migration/raw/master/doc/images/cloudforms_vms_1.png

**Comment by bthurber** [comment]
I submitted a large PR last evening that should have new screenshots.  :)

You an view my fork here to verify:  https://github.com/bthurber/RHS-Infrastructure_Migration

**Comment by mperezco** [comment]
Merged.
Thanks @cbolz @bthurber !
