### ISSUE TITLE
Add "how to create a conversion host in OSP" to the IMS 1.1 documentation

### ISSUE THREAD

**Issue by mperezco** [RedHatDemos/RHS-Infrastructure_Migration#77]

**Comment by mperezco** [comment]
Add chapter on how to add conversion host to OSP to the Deployment Guide:
https://github.com/RedHatDemos/RHS-Infrastructure_Migration/blob/ims_1.1/doc/insfrastructure_migration-deployment_guide.adoc

**Comment by mmmmmmpc** [comment]
Added
