### ISSUE TITLE
Running "Unconfigure" messes up Ansible Embedded configuration

### ISSUE THREAD

**Issue by mperezco** [RedHatDemos/RHS-Infrastructure_Migration#90]

**Comment by mperezco** [comment]
With a configured CloudForms instance, when running the "unconfigure"playbook, cleans up the database. 
This clean-up messes up the Ansible Embedded configuration that, afterwards refuses to start.

**Comment by mperezco** [comment]
I found  two ways to approach it. 
1.- Check database records of Embedded Ansible and dump them before cleanup, then restore later
2.- Find Ansible embedded initialization sequence to see how it can be re-run without issues.

**Comment by mmmmmmpc** [comment]
Drop Ansible object from DB before shutdown service
Remove awx database
Cleanup CF database
All in the unconfigure role.
